name: CI Pipeline
 
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
 
jobs:
    build:
        runs-on: ubuntu-latest
   
        steps:
        - name: Checkout code
          uses: actions/checkout@v4
 
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
        
            pip install flake8 pytest
       
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

          name: flake1
          run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

          name: pytest
          run: pytest -v